package com.thirstysgame.data.model

import com.google.gson.annotations.SerializedName

/**
 * Data models for the Thirsty's Game app.
 * These models correspond to the JSON artifacts generated by the Python agent.
 */

/**
 * Community insight from various sources.
 */
data class CommunityInsight(
    val source: String,
    val content: String,
    val sentiment: Float,
    val topics: List<String>,
    val author: String,
    val timestamp: String,
    val engagement: Map<String, Int>,
    val category: String,
    val priority: Float
)

/**
 * Feature proposal derived from community insights.
 */
data class FeatureProposal(
    val title: String,
    val description: String,
    @SerializedName("source_insights")
    val sourceInsights: List<String>,
    val category: String,
    @SerializedName("monetization_type")
    val monetizationType: String,
    val priority: Float,
    @SerializedName("f2p_compliant")
    val f2pCompliant: Boolean,
    @SerializedName("guardrail_notes")
    val guardrailNotes: List<String>,
    @SerializedName("comparative_notes")
    val comparativeNotes: List<String>,
    @SerializedName("created_at")
    val createdAt: String
)

/**
 * Summary of community insights.
 */
data class InsightsSummary(
    @SerializedName("total_count")
    val totalCount: Int,
    @SerializedName("avg_sentiment")
    val avgSentiment: Float,
    @SerializedName("top_topics")
    val topTopics: List<List<Any>>, // [topic, count] pairs
    val sources: List<String>
)

/**
 * Storefront item for cosmetic purchases.
 */
data class StorefrontItem(
    val id: String,
    val name: String,
    val type: String,
    val price: Int,
    val currency: String,
    val description: String
)

/**
 * F2P policy summary.
 */
data class F2PPolicySummary(
    @SerializedName("core_principles")
    val corePrinciples: List<String>,
    @SerializedName("what_we_offer")
    val whatWeOffer: List<String>,
    @SerializedName("what_we_never_do")
    val whatWeNeverDo: List<String>
)

/**
 * Complete app data bundle from agent pipeline.
 */
data class AppDataBundle(
    val version: String,
    @SerializedName("generated_at")
    val generatedAt: String,
    @SerializedName("insights_summary")
    val insightsSummary: InsightsSummary,
    val proposals: List<FeatureProposal>,
    @SerializedName("f2p_policy_summary")
    val f2pPolicySummary: F2PPolicySummary,
    @SerializedName("storefront_items")
    val storefrontItems: List<StorefrontItem>
)
